Класс Student
===

Этот класс создан ддля проверки средних результатов студентов
---

Для начало импрортируем файл

    >>> from files_py import student

Проверим некоторые параметры класса:

    >>> data = student.Student('Сергей Бритьев')
    >>> data.results_dict
    'Студент - Сергей Бритьев:\n[]\n{}'

Мы видим что данных не хватает, но предже чем идти дальше, мы посмотрим что будет в инном случае

    >>> data = student.Student('cергей Бритьев')
    Traceback (most recent call last):
    ...
    ValueError: Ошибка переданного ФИО

В случае передачи ФИО с маленьких букв будет ошибка

Посмотрим как сделать полную сводку информации о студенте

    >>> data = student.Student('Бочкин Cергей Бритьевич')
    >>> data('астрономия', 80, 5)
    >>> data.results_dict
    "Студент - Бочкин Cергей Бритьевич:\n['exam : астрономия = 80.0', 'grade : астрономия = 5.0']\n{'exam': 80.0, 'grade': 5.0}"


Так же возможна пополнение информации о студенте

    >>> data = student.Student('Бочкин Cергей Бритьевич')
    >>> data('астрономия', 80, 5)
    >>> data('этикет', 90, 4)
    >>> data.results_dict
    "Студент - Бочкин Cергей Бритьевич:\n['exam : астрономия = 80.0', 'exam : этикет = 90.0', 'grade : астрономия = 5.0', 'grade : этикет = 4.0']\n{'exam': 85.0, 'grade': 4.5}"


Изначально досутпные предметы есть в файле subject.csv и по ним идёт проверка, то есть не возможно добавить студента с не существующим предметом

    >>> data = student.Student('Бочкин Cергей Бритьевич')
    >>> data('физика', 80, 5)
    Traceback (most recent call last):
    ...
    ValueError: Данного предмета не существует

Так же нет возможности переплюнуть всех студентов, например получить по тесту 101 или выше баллов

    >>> data = student.Student('Бочкин Cергей Бритьевич')
    >>> data('астрономия', 101, 5)
    Traceback (most recent call last):
    ...
    ValueError: Ошибка переданного значения: от 0 до 100

Или же получить оценку выше 5 или ниже 2

    >>> data = student.Student('Бочкин Cергей Бритьевич')
    >>> data('астрономия', 90, 6)
    Traceback (most recent call last):
    ...
    ValueError: Ошибка переданного значения: от 2 до 5